/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function init(libPath: string): Promise<void>
export declare function getVersion(): number
export declare class Config {
  load(fileName: string): number
  getString(section: string, entry: string, default: string): string
  getInt(section: string, entry: string, default: number): number
  setString(section: string, entry: string, value: string): number
  setInt(section: string, entry: string, value: number): number
  save(fileName: string): number
}
export type T2SDK = T2Sdk
export declare class T2Sdk {
  readonly config: Config
  constructor()
}
